### ISSUE TITLE
'GridWorldMDP' object has no attribute 'size'

### ISSUE THREAD

**Issue by arnaghosh** [zafarali/emdp#18]
Error encountered while running the example code for gridworld - "build_SB_example35" function.
This is because calling the GridWorldMDP `__init__()` function calls the `__init__()` for MDP class, which in turn runs the `reset()` function. The overloaded reset() function for the GridWorldMDP class is then called instead of the `MDP.reset()`. 
A potential solution is to define self.size, self.human_state and self.has_absorbing_states prior to calling `super.__init__()`. However, a more object-oriented solution is probably possible.

**Comment by zafarali** [comment]
Hi thanks for reporting!
I think this might have been caused by
 246086d9376b72a807001113f80c39d5e30405e1

If you want to send a possible solution or a PR with that reverted I’ll be
happy to accept it.

**Comment by zafarali** [comment]
I fixed the issue in a recent commit. Sorry for the trouble. If you want to suggest a better fix I am happy to consider. I will leave this issue open.

**Comment by arnaghosh** [comment]
Hey thanks for your prompt reply. I feel removing the GridWorldMDP class reset function doesn't set the self.human_state at the initialization. This may affect other functions that use this variable to render the env graphically. 
I feel assigning the extra variables (like size) that are not required by the MDP init prior to calling `super.__init__` is a better workaround. This is what it would look like:
`class GridWorldMDP(MDP):
    def __init__(self, P, R, gamma, p0, terminal_states, size, seed=1337, skip_check=False,
                 convert_terminal_states_to_ints=False):
        """
        (!) if terminal_states is not empty then there will be an absorbing state. So
            the actual number of states will be size x size + 1
            if there is a terminal state, it should be the last one.
        :param P: Transition matrix |S| x |A| x |S|
        :param R: Transition matrix |S| x |A|
        :param gamma: discount factor
        :param p0: initial starting distribution
        :param terminal_states: Must be a list of (x,y) tuples.  use skip_terminal_state_conversion if giving ints
        :param size: the size of the grid world (i.e there are size x size (+ 1)= |S| states)
        :param seed:
        :param skip_check:
        """
        if not convert_terminal_states_to_ints:
            terminal_states = list(map(lambda tupl: int(size * tupl[0] + tupl[1]), terminal_states))
        self.size =  size
        self.human_state = (None, None)
        self.has_absorbing_state = len(terminal_states) > 0
        super().__init__(P, R, gamma, p0, terminal_states, seed=seed, skip_check=skip_check)
        # self.reset()

    def reset(self):
        super().reset()
        self.human_state = self.unflatten_state(self.current_state)`

**Comment by arnaghosh** [comment]
Created a PR (#19) with this change.

**Comment by zafarali** [comment]
Thanks for fixing this! It is now in the master branch with the `reset()` function from GridWorldMDP passing tests.
